- name: install dependencies
  package:
    name: "{{ item }}"
    state: "present"
  with_items:
    - unclutter
    - xdotool

- name: Download my_package
  get_url:
    url="https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
    dest="/tmp/google-chrome-stable_current_amd64.deb"

- name: Install my_package
  apt: deb="/tmp/google-chrome-stable_current_amd64.deb"

- name: Patch gdm3 for automatic login
  ansible.builtin.copy:
    src: templates/custom.conf
    dest: /etc/gdm3/custom.conf
    remote_src: yes

- name: Copy koisk to home dir of user
  ansible.builtin.copy:
    src: templates/koisk.sh
    dest: /home/user/koisk.sh
    remote_src: yes





