- name: install dependencies
  package:
    name: "{{ item }}"
    state: "present"
  with_items:
    - unclutter
    - xdotool

- name: Download chrome
  get_url:
    url="https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
    dest="/tmp/google-chrome-stable_current_amd64.deb"

- name: Install chrome
  apt: deb="/tmp/google-chrome-stable_current_amd64.deb"

- name: Patch gdm3 for automatic login
  ansible.builtin.copy:
    src: /etc/ansible/roles/kiosk/templates/custom.conf
    dest: /etc/gdm3/custom.conf

- name: Copy koisk to home dir of user
  ansible.builtin.copy:
    src: /etc/ansible/roles/kiosk/templates/kiosk.sh
    dest: /home/fotocadeau/kiosk.sh

- name: make this script executable
  command: chmod +x /home/fotocadeau/kiosk.sh

- name: Copy koisk to home dir of user
  ansible.builtin.copy:
    src: /etc/ansible/roles/kiosk/templates/kiosk.desktop
    dest: /home/fotocadeau/.config/autostart/kiosk.desktop

- name: reboot the machine
  ansible.builtin.reboot: