- name: install dependencies
  package:
    name: "{{ item }}"
    state: "present"
  with_items:
    - unclutter
    - xdotool

- name: Download chrome
  get_url:
    url="https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
    dest="/tmp/google-chrome-stable_current_amd64.deb"

- name: Install chrome
  apt: deb="/tmp/google-chrome-stable_current_amd64.deb"

- name: Patch gdm3 for automatic login
  ansible.builtin.copy:
    src: /etc/ansible/roles/kiosk/templates/custom.conf
    dest: /etc/gdm3/custom.conf

- name: Copy koisk to home dir of user
  ansible.builtin.copy:
    src: /etc/ansible/roles/kiosk/templates/kiosk.sh
    dest: /home/user/kiosk.sh

- name: Copy systemd service file to server
  copy:
    src: /etc/ansible/roles/kiosk/templates/kiosk.service
    dest: /etc/systemd/system
    owner: root
    group: root

- name: Start kiosk
  systemd:
    name: kiosk
    state: started
    enabled: yes

- name: reboot the machine
  ansible.builtin.reboot:


